[package]
name = "day12"
version = "0.1.0"
authors = ["Robert Lasch <robert.lasch0@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.0"

[[bin]]
name = "day12"
path = "main.rs"
